import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/ui/Header';
import RootProviders from '@/providers/RootProviders';
import Script from 'next/script';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={''}>
        <Header />
        <RootProviders>{children}</RootProviders>

        <div id="modal-portal" />
        <Script
          defer
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY}&autoload=false`}
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}
