// import { TMainCardList, TMypageCardList } from '@/types/card';
// import testImg from '@/assets/img/test-img.png';

// export const mainListMock: Record<string, TMainCardList[]> = {
//   mostViewPlans: [
//     {
//       title: '제주 서쪽 코스',
//       placeCategory: ['애월', '협제', '서귀포'],
//       startDate: '2024-01-01',
//       endDate: '2024-01-04',
//       people: 3,
//       transportation: 'PUBLIC_TRANSPORT',
//       totalCost: 1000000,
//       thumbnail: testImg,
//     },
//     {
//       title: '제주 서쪽 코스2',
//       placeCategory: ['애월', '협제', '서귀포'],
//       startDate: '2024-01-01',
//       endDate: '2024-01-04',
//       people: 3,
//       transportation: 'PUBLIC_TRANSPORT',
//       totalCost: 1000000,
//       thumbnail: testImg,
//     },
//     {
//       title: '제주 서쪽 코스3',
//       placeCategory: ['애월', '협제', '서귀포'],
//       startDate: '2024-01-01',
//       endDate: '2024-01-04',
//       people: 3,
//       transportation: 'PUBLIC_TRANSPORT',
//       totalCost: 1000000,
//       thumbnail: testImg,
//     },
//     {
//       title: '제주 서쪽 코스4',
//       placeCategory: ['애월', '협제', '서귀포'],
//       startDate: '2024-01-01',
//       endDate: '2024-01-04',
//       people: 3,
//       transportation: 'PUBLIC_TRANSPORT',
//       totalCost: 1000000,
//       thumbnail: testImg,
//     },
//     {
//       title: '제주 서쪽 코스5',
//       placeCategory: ['애월', '협제', '서귀포'],
//       startDate: '2024-01-01',
//       endDate: '2024-01-04',
//       people: 3,
//       transportation: 'PUBLIC_TRANSPORT',
//       totalCost: 1000000,
//       thumbnail: testImg,
//     },
//   ],
//   mostRecentPlans: [
//     {
//       title: '경기 남부 코스',
//       placeCategory: ['수원', '용인', '화성'],
//       startDate: '2024-01-01',
//       endDate: '2024-01-04',
//       people: 5,
//       transportation: 'CAR',
//       totalCost: 1000000,
//       thumbnail: testImg,
//     },
//   ],
//   HongdaeHotPlans: [
//     {
//       title: '홍대 투어',
//       placeCategory: ['홍대'],
//       startDate: '2024-01-01',
//       endDate: '2024-01-04',
//       people: 5,
//       transportation: 'CAR',
//       totalCost: 1000000,
//       thumbnail: testImg,
//     },
//   ],
// };

// export const myPlannersMock: TMypageCardList[] = [
//   {
//     planId: 1,
//     title: '제주 동쪽 2박 3일 여행1',
//     created_at: new Date('2025-01-01'),
//     thumbnail: testImg,
//     categories: ['애월', '협재', '서귀포'],
//     status: 'PUBLIC',
//   },
//   {
//     planId: 2,
//     title: '제주 동쪽 2박 3일 여행2',
//     created_at: new Date('2025-01-01'),
//     thumbnail: testImg,
//     categories: ['애월', '협재', '서귀포'],
//     status: 'PUBLIC',
//   },
//   {
//     planId: 3,
//     title: '제주 동쪽 2박 3일 여행3',
//     created_at: new Date('2025-01-01'),
//     thumbnail: testImg,
//     categories: ['애월', '협재', '서귀포'],
//     status: 'PUBLIC',
//   },
//   {
//     planId: 4,
//     title: '제주 동쪽 2박 3일 여행4',
//     created_at: new Date('2025-01-01'),
//     thumbnail: testImg,
//     categories: ['애월', '협재', '서귀포'],
//     status: 'PUBLIC',
//   },
// ];

// export const dibsPlannersMock: TMypageCardList[] = [
//   {
//     planId: 1,
//     title: '찜한 제주 동쪽 2박 3일 여행1',
//     created_at: new Date('2025-01-01'),
//     thumbnail: testImg,
//     categories: ['애월', '협재', '서귀포'],
//     status: 'PUBLIC',
//   },
//   {
//     planId: 2,
//     title: '찜한 제주 동쪽 2박 3일 여행2',
//     created_at: new Date('2025-01-01'),
//     thumbnail: testImg,
//     categories: ['애월', '협재', '서귀포'],
//     status: 'PUBLIC',
//   },
//   {
//     planId: 3,
//     title: '찜한 제주 동쪽 2박 3일 여행3',
//     created_at: new Date('2025-01-01'),
//     thumbnail: testImg,
//     categories: ['애월', '협재', '서귀포'],
//     status: 'PUBLIC',
//   },
//   {
//     planId: 4,
//     title: '찜한 제주 동쪽 2박 3일 여행4',
//     created_at: new Date('2025-01-01'),
//     thumbnail: testImg,
//     categories: ['애월', '협재', '서귀포'],
//     status: 'PUBLIC',
//   },
// ];
